### PR TITLE
chore: Fix build warnings

### LINKED ISSUE #1278: Reduce the build warnings
### Chore

**Description**
The warnings during builds have increased a lot and need to be eliminated.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #1278 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ private void checkRestrictAll() {
         boolean restrictAll = true;
 
         for (Ticket ticket : ticketSettingsViewModel.getTickets().getValue()) {
-            if (ticket.isCheckinRestricted == null || !ticket.isCheckinRestricted) {
```
Comment (mishuvs) [inline app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java]: Why? What if it's null?

File: app/src/main/java/com/eventyay/organizer/data/order/Statistics.java [hunk 2]
```diff
@@ -27,7 +27,7 @@
     public Long cancelled;
     public Long pending;
     public Long placed;
-    public Long total;
+    public long total;
```
Comment (mishuvs) [inline app/src/main/java/com/eventyay/organizer/data/order/Statistics.java]: Why?

File: app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java [hunk 3]
```diff
@@ -100,7 +100,7 @@ private void checkRestrictAll() {
...
+            if (!ticket.isCheckinRestricted) {
```
Comment (mishuvs) [inline app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java]: Why? What if it's null?

File: app/src/main/java/com/eventyay/organizer/data/order/Statistics.java (hunk 2 above)
Comment (sridharjajoo) [reply app/src/main/java/com/eventyay/organizer/data/order/Statistics.java]: Check this [link](https://stackoverflow.com/questions/42872201/data-binding-safeunbox-warning) . I followed the same thing in one of the earlier P.R as well where the same problem was addressed.

File: app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java (hunk 3 above)
Comment (sridharjajoo) [reply app/src/main/java/com/eventyay/organizer/core/settings/restriction/CheckInRestrictions.java]: I changed the type from Boolean to boolean. A **boolean** can never be null. It can be either true or false.

**Comment by sridharjajoo** [comment]
@Masquerade0097 This is what it looks like after the build
screenshot from 2018-07-30 19-46-50

**Comment by Masquerade0097** [comment]
@sridharjajoo Can't the warning `The rule --keep public class extends java.lang.annotation.Annotation {` be resolved ?

**Comment by sridharjajoo** [comment]
@Masquerade0097 This warning is present in studio 3.1 and is resolved in version 3.2
