### PR TITLE
fix: Prevent Account section's action bar title from changing

### LINKED ISSUE #1892: Action Bar title changes when clicking on email
**Describe the bug**
When clicking on email to redirect to mailing app, ActionBar title change from "<Account Name>" to "OrganizerDetailActivity"
Besides, it is also illogical that the person who owning the email want to send an email to himself/herself

**Screenshots**
ezgif-2-49d310e68ead

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1892

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java [hunk 1]
```diff
@@ -185,6 +186,25 @@ public void onStart() {
...
+            String firstName = user.getFirstName();
+            String lastName = user.getLastName();
+            String email = user.getEmail();
+
+            if (firstName != null)
+                ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle(
+                    firstName + " " + lastName);
+            else
+                ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle(email);
+        }
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Where was it previously being set?

**Comment by iamareebjamal** [comment]
@anhanh11001 That's set in AndroidManifest

File: app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java (hunk 1 above)
Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: In the XML file.

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Why wasn't it working?

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Whenever the fragment was being resumed, the title was getting changed to `OrganizerDetailActivity` because of the `getTitle()` method of the BaseFragment.

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: The `onResume()` method in the BaseFragment:

```
@Override
public void onResume() {
    super.onResume();
    setTitle(getString(getTitle()));
}
```

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: So why not override `getTitle`?

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: `getTitle()` is already overridden and `OrganizerDetailActivity` is being set from there. Is it possible to set the organizer name from there since it takes int resource value and we cannot change values in strings.xml programatically at runtime?

Comment (iamareebjamal) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Got it

File: app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java [hunk 2]
```diff
@@ -185,6 +186,25 @@ public void onStart() {
...
+        if (user != null) {
+            String firstName = user.getFirstName();
+            String lastName = user.getLastName();
+            String email = user.getEmail();
+
+            if (firstName != null)
+                ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle(
+                    firstName + " " + lastName);
+            else
+                ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle(email);
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Eliminate duplication `((AppCompatActivity) getActivity()).getSupportActionBar()`

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java]: Updated.
