### PR TITLE
fix: mutiple toast message on creating event

### LINKED ISSUE #1981: Error and Success toast message are shown multiple times while creating an event
**Describe the bug**

The onStart function has error and success livedata being observed because of which the toast messages are displayed every time the screen is made active.

**To Reproduce**

1. Go to create event activity
2. Click on next without typing or setting any date
3. A toast message will be displayed
4. Now lock the phone and unlock it, the same toast message will be displayed again.
5. The same goes for the success message after uploading a photo.
6. The main problem arises when we rectify the error and upload a photo, now again on resuming the activity by any means will throw the unnecessary rectified error message and success message. 

**Expected behavior**

The toast message should be shown only once.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G4 Plus|
|Android Version|Oreo 8.1    |

**Would you like to work on the issue?**

- [ ] Yes

### PR DESCRIPTION
**Pull request by rishabh-997**
Fixes #1981 

Checklist:

- [x] I have checked for PMD and check-style issues 
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream development branch.

Changes: 
I made a function to empty the string after a toast message is displayed as the onError variable was not updated after removal of error and it was observed and displayed every time the activity started again. I also checked for empty messages and did not displayed them if they were null.
- [change 1](https://github.com/fossasia/open-event-organizer-android/compare/development...rishabh-997:develop?expand=1#diff-ef13da30f7163ed5cfe918e02b09ecb1)
- [change 2](https://github.com/fossasia/open-event-organizer-android/compare/development...rishabh-997:develop?expand=1#diff-ccd9f34b0b9f443f63acbf0a4e442e09)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-orga-app/open-event-orga-app/pullRequest?prid=4568976&bid=15359573)

File: app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java [hunk 1]
```diff
@@ -144,7 +147,10 @@ public void showProgress(boolean show) {
 
     @Override
     public void onSuccess(String message) {
-        Toast.makeText(getActivity(), message, Toast.LENGTH_SHORT).show();
+        if(!message.equals("")){
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java]: Codacy Issue found: [Position literals first in String comparisons](https://app.codacy.com/app/fossasia/open-event-orga-app/pullRequest?prid=4568976)

File: app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java [hunk 2]
```diff
@@ -134,7 +134,10 @@ private void setOriginalImageUrl(ImageUrl imageUrl) {
 
     @Override
     public void showError(String error) {
-        Toast.makeText(getActivity(), error, Toast.LENGTH_SHORT).show();
+        if(!error.equals("")) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java]: Codacy Issue found: [Position literals first in String comparisons](https://app.codacy.com/app/fossasia/open-event-orga-app/pullRequest?prid=4568976)

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
It's a workaround. Not a fix

**Comment by rishabh-997** [comment]
> It's a workaround. Not a fix

sir, the problem was that the error was not being updated after being resolved. What changes will you suggest?

File: app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java [hunk 3]
```diff
@@ -132,7 +132,6 @@ public boolean verify() {
             onError.setValue("Please enter date in correct format");
             return false;
         }
-
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventViewModel.java]: revert

File: app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java [hunk 4]
```diff
@@ -57,19 +57,18 @@ public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup c
...
     @Override
     public void onStart() {
         super.onStart();
         binding.setEvent(createEventViewModel.getEvent());
-        createEventViewModel.getSuccessMessage().observe(this, this::onSuccess);
-        createEventViewModel.getErrorMessage().observe(this, this::showError);
         createEventViewModel.getCloseState().observe(this, isClosed -> close());
         createEventViewModel.getProgress().observe(this, this::showProgress);
         createEventViewModel.getEvent().isTaxEnabled = true;
-
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/event/create/EventDetailsStepThree.java]: revert

**Review by iamareebjamal — APPROVED** [review]
