### PR TITLE
fix: Prevent headers from shifting down in Tickets fragment

### LINKED ISSUE #1754: Ticket section goes down after navigating back from print fragment
**Describe the bug**
Ticket section slides down after navigating back from print fragment

**Screenshots**
ezgif-2-0a6678d9ccd7

**Would you like to work on the issue?**
Open to all

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #1754 

GIF for the change: 

Prevent headers from shifting down in Tickets fragment

### CODE REVIEW

File: app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java [hunk 1]
```diff
@@ -104,25 +110,26 @@ public void openCreateTicketFragment() {
...
-        adapterDataObserver = new RecyclerView.AdapterDataObserver() {
-            @Override
-            public void onChanged() {
-                decoration.invalidateHeaders();
-            }
-        };
-
-        ViewUtils.setRecyclerViewScrollAwareFabBehaviour(recyclerView, binding.createTicketFab);
-
+        if (!initialized) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java]: Can't be just check ticketAdapter == null

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java]: Yes that would be better.

Comment (ShridharGoel) [reply app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java]: Updated.
